In [16]:
# methods of pandas :-
import pandas as pd
d = {
    "name":["anna","jiva","chinmay","shiv"],
    "salary":[100,200,300,400]
}
df = pd.DataFrame(d)
df["holiday"] = df["salary"] // 100
df["decrement"] = [10,20,30,40]
df.drop(["salary"],axis = 1)          # per original value mai change karne ke liye inplace = true lagna hoga
#  in drop method axis 1 means column

      name  holiday  decrement
0     anna        1         10
1     jiva        2         20
2  chinmay        3         30
3     shiv        4         40

# IN the case of the Rows there will be  : -
(add the rows)

1. loc  : - Label based->  in this you need to pass column name and index

2. iloc : - index based -> in this need to pass the index numbers of the value

In [18]:
import pandas as pd
d = {
    "name":["anna","jiva","chinmay","shiv"],
    "salary":[100,200,300,400]
}
df = pd.DataFrame(data=d)

# getting single element :-
print(df.loc[2,"name"])
print(df.iloc[2,0])

# getting single row :-
print(df.loc[2])

# getting multiple rows using iloc :-
print("\n",df.iloc[0:3])

# getting multiple rows using loc :-
print("\n",df.loc[0:3])
print("\n",df.loc[0:3,"name"])
print("\n",df.loc[0:3,"salary"])

chinmay
chinmay
name      chinmay
salary        300
Name: 2, dtype: object

       name  salary
0     anna     100
1     jiva     200
2  chinmay     300

       name  salary
0     anna     100
1     jiva     200
2  chinmay     300
3     shiv     400

 0       anna
1       jiva
2    chinmay
3       shiv
Name: name, dtype: object

 0    100
1    200
2    300
3    400
Name: salary, dtype: int64

    name
0  anna
1  jiva

    salary
0     100
1     200
2     300

In [25]:
#  getting sub data set  :-
print(df)
# by loc :
df1 =df.iloc[0:2,[0]]
print("\n", df1)
# by iloc :
df2 = df.loc[0:2,["salary"]]
print("\n",df2)

      name  salary
0     anna     100
1     jiva     200
2  chinmay     300
3     shiv     400

    name
0  anna
1  jiva

    salary
0     100
1     200
2     300

In [35]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 45000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)
print(df)

print("\n",df.loc[1,"Name"])
print("\n",df.iloc[1,2])
print("\n",df.loc[1:2])
print("\n",df.iloc[1:2])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   60000           3
2     103   Raj    Finance   55000           5
3     104  Sara         IT   70000           4
4     105  John      Sales   45000           1
5     106  Neha         HR   52000           3

 Riya

 HR

    Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   60000           3
2     103   Raj    Finance   55000           5

    Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   60000           3

In [38]:
# json : -
import pandas as pd
url ="https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/student-data.json"
df = pd.read_json(url)
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [44]:
print("\n",df.loc[1,"name"])
print("\n",df.iloc[1,2])
print("\n",df.loc[1:2])
print("\n",df.iloc[1:2])
print("\n",df.loc[2,"name"])
print("\n",df.iloc[2,0])
print("\n",df.loc[2])
df.drop(["gender"],axis=1)

 rajesh

 96

       name gender  physics  maths  english
1   rajesh   Male       96    100       95
2  moorthy   Male       89     90       70

      name gender  physics  maths  english
1  rajesh   Male       96    100       95

 moorthy

 moorthy

 name       moorthy
gender        Male
physics         89
maths           90
english         70
Name: 2, dtype: object

       name  physics  maths  english
0      arun       88     87       78
1    rajesh       96    100       95
2   moorthy       89     90       70
3      raja       30     25       40
4      usha       67     45       78
5     priya       56     46       78
6    Sundar       12     67       67
7   Kavitha       78     71       67
8    Dinesh       56     45       67
9      Hema       71     90       23
10    Gowri      100    100      100
11      Ram       78     55       47
12  Murugan       34     89       78
13  Jenifer       67     88       90

In [69]:
df["science"] = df["english"]
# print(df)

print(df.iloc[[3,8], 0])
print(df.iloc[3:9:5, 0])    # another way
#filter:
df[df["maths"] < 60]

3      raja
8    Dinesh
Name: name, dtype: object
3      raja
8    Dinesh
Name: name, dtype: object

      name  gender  physics  maths  english  science
3     raja    Male       30     25       40       40
4     usha  Female       67     45       78       78
5    priya  Female       56     46       78       78
8   Dinesh    Male       56     45       67       67
11     Ram    Male       78     55       47       47