In [9]:
import pandas as pd
url = "https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/file1.json"
df = pd.read_json(url)
print(df)


# head :-        for getting  starting row
print(df.head())

print("\n",df.head(2))
print("\n",df.head(-1)) # -> remove the value from end

# tail :-   for getting last rows
print("\n",df.tail())
print("\n",df.tail(2))
print("\n",df.tail(-1))   # -> remove the value from start

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567
       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

       name  roll no
0  dheeraj      123
1    kunal     1234

        name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356

        name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

       name  roll no
3  praveen    12356
4   anjali  1234567

        name  roll no
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

In [18]:
import pandas as pd
url = "https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/file1.json"
df = pd.read_json(url)
print(df)

# shape :-
df.shape         # gives row & column number

print("\n")
#info() :-
df.info()       # information about the rows & columns & inside it null value is present or not (not mathematically infomation)
print("\n")
df.info(verbose=False)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 2 entries, name to roll no
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [32]:
import pandas as pd
url = "https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/file1.json"
df = pd.read_json(url)
print(df)
print("\n")

# rename:-
df.rename(columns={"name":"student name "}) # original data donot change
print("\n",df)
df.rename(columns={"name":"student name ","roll no":"student ID"},inplace=True)  # original data change
print("\n",df)

       name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567



        name  roll no
0   dheeraj      123
1     kunal     1234
2  abhishek    12345
3   praveen    12356
4    anjali  1234567

   student name   student ID
0       dheeraj         123
1         kunal        1234
2      abhishek       12345
3       praveen       12356
4        anjali     1234567

In [34]:
import pandas as pd
url = "https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/file1.json"
df = pd.read_json(url)
df.describe()       # work only mathematics  that give us : - count , mean , std ,percentage ,min/max

            roll no
count  5.000000e+00
mean   2.521250e+05
std    5.492329e+05
min    1.230000e+02
25%    1.234000e+03
50%    1.234500e+04
75%    1.235600e+04
max    1.234567e+06

In [44]:
import pandas as pd
data = {
    "Emp_ID" : [101,102,103,104,105],
    "Name": ["Anna","Jiva","NIkhil","Elsa","Ri"],
    "Department":["IT","fashion","Music","cse","game"],
    "Salary" : [50000,4000000,67000,23000,34000],
    "Experiencce":[1,4,5,3,2]
}

df = pd.DataFrame(data)
print(df)

print("\n",df.head(3))
print("\n",df.tail(2))
print("\n",df.head(-2))
print("\n",df.tail(-3))
print("\n",df.shape)
print("\n",df.info())
print("\n",df.info(verbose=False))
print("\n",df.describe())
df.rename(columns={"deparment":"Field"})

   Emp_ID    Name Department   Salary  Experiencce
0     101    Anna         IT    50000            1
1     102    Jiva    fashion  4000000            4
2     103  NIkhil      Music    67000            5
3     104    Elsa        cse    23000            3
4     105      Ri       game    34000            2

    Emp_ID    Name Department   Salary  Experiencce
0     101    Anna         IT    50000            1
1     102    Jiva    fashion  4000000            4
2     103  NIkhil      Music    67000            5

    Emp_ID  Name Department  Salary  Experiencce
3     104  Elsa        cse   23000            3
4     105    Ri       game   34000            2

    Emp_ID    Name Department   Salary  Experiencce
0     101    Anna         IT    50000            1
1     102    Jiva    fashion  4000000            4
2     103  NIkhil      Music    67000            5

    Emp_ID  Name Department  Salary  Experiencce
3     104  Elsa        cse   23000            3
4     105    Ri       game   34000            2

 (5, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Emp_ID       5 non-null      int64
 1   Name         5 non-null      object
 2   Department   5 non-null      object
 3   Salary       5 non-null      int64
 4   Experiencce  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

 None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 5 entries, Emp_ID to Experiencce
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

 None

            Emp_ID        Salary  Experiencce
count    5.000000  5.000000e+00     5.000000
mean   103.000000  8.348000e+05     3.000000
std      1.581139  1.769479e+06     1.581139
min    101.000000  2.300000e+04     1.000000
25%    102.000000  3.400000e+04     2.000000
50%    103.000000  5.000000e+04     3.000000
75%    104.000000  6.700000e+04     4.000000
max    105.000000  4.000000e+06     5.000000

   Emp_ID    Name Department   Salary  Experiencce
0     101    Anna         IT    50000            1
1     102    Jiva    fashion  4000000            4
2     103  NIkhil      Music    67000            5
3     104    Elsa        cse    23000            3
4     105      Ri       game    34000            2

In [52]:
import pandas as pd
url = "https://raw.githubusercontent.com/anjali801/Data-science-45-internship/main/file1.json"
df = pd.read_json(url)

#add single column
df["salary"] = [50000,4000000,67000,23000,34000]
print("\n",df)

# for getting single column data
df["name"]

        name  roll no   salary
0   dheeraj      123    50000
1     kunal     1234  4000000
2  abhishek    12345    67000
3   praveen    12356    23000
4    anjali  1234567    34000

0     dheeraj
1       kunal
2    abhishek
3     praveen
4      anjali
Name: name, dtype: object

In [60]:
import pandas as pd
d = {
    "name":["anju","sara","shivi","priya","moti"],
    "salary":[100,250,300,450,760]
}
d = pd.DataFrame(data=d)
# add column
d["marks"] = [20 , 34,67,87,23]
d["first_installiation_of_salary"] = d["salary"] / 2
d

    name  salary  marks  first_installiation_of_salary
0   anju     100     20                           50.0
1   sara     250     34                          125.0
2  shivi     300     67                          150.0
3  priya     450     87                          225.0
4   moti     760     23                          380.0