# sorting :
- by default ascending
- ascending = false

#delete : -  
delete are of two types :     
- hard delete
- soft delete


#-In every Data three block always available :         
- created at
- updated at
- deleted at

In [8]:
# sorting
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
#ascending :
df.sort_values("english")

#decending:
df.sort_values("english",ascending=False)

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
7   Kavitha  Female       78     71       67
6    Sundar    Male       12     67       67
8    Dinesh    Male       56     45       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [9]:
# another way :
df.sort_values(by=["name"])

       name  gender  physics  maths  english
8    Dinesh    Male       56     45       67
10    Gowri  Female      100    100      100
9      Hema  Female       71     90       23
13  Jenifer  Female       67     88       90
7   Kavitha  Female       78     71       67
12  Murugan    Male       34     89       78
11      Ram    Male       78     55       47
6    Sundar    Male       12     67       67
0      arun    Male       88     87       78
2   moorthy    Male       89     90       70
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
4      usha  Female       67     45       78

In [10]:
df.sort_values(by=["name"],ascending = False)

       name  gender  physics  maths  english
4      usha  Female       67     45       78
1    rajesh    Male       96    100       95
3      raja    Male       30     25       40
5     priya  Female       56     46       78
2   moorthy    Male       89     90       70
0      arun    Male       88     87       78
6    Sundar    Male       12     67       67
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
7   Kavitha  Female       78     71       67
13  Jenifer  Female       67     88       90
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
8    Dinesh    Male       56     45       67

In [11]:
df.sort_values(by=["english","maths"],ascending=[False , True])

       name  gender  physics  maths  english
10    Gowri  Female      100    100      100
1    rajesh    Male       96    100       95
13  Jenifer  Female       67     88       90
4      usha  Female       67     45       78
5     priya  Female       56     46       78
0      arun    Male       88     87       78
12  Murugan    Male       34     89       78
2   moorthy    Male       89     90       70
8    Dinesh    Male       56     45       67
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
11      Ram    Male       78     55       47
3      raja    Male       30     25       40
9      Hema  Female       71     90       23

In [12]:
# a to z sorting :-
df['name']= df['name'].str.lower()
df.sort_values("name")

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

In [16]:
df["science"] = df["maths"]    # column add
print(df)
# row
df.loc[14] = ["anjali","Female",92,97,90,88]
df

       name  gender  physics  maths  english  science
0      arun    Male       88     87       78       87
1    rajesh    Male       96    100       95      100
2   moorthy    Male       89     90       70       90
3      raja    Male       30     25       40       25
4      usha  Female       67     45       78       45
5     priya  Female       56     46       78       46
6    sundar    Male       12     67       67       67
7   kavitha  Female       78     71       67       71
8    dinesh    Male       56     45       67       45
9      hema  Female       71     90       23       90
10    gowri  Female      100    100      100      100
11      ram    Male       78     55       47       55
12  murugan    Male       34     89       78       89
13  jenifer  Female       67     88       90       88
14   anjali  Female       92     97       90       97

       name  gender  physics  maths  english  science
0      arun    Male       88     87       78       87
1    rajesh    Male       96    100       95      100
2   moorthy    Male       89     90       70       90
3      raja    Male       30     25       40       25
4      usha  Female       67     45       78       45
5     priya  Female       56     46       78       46
6    sundar    Male       12     67       67       67
7   kavitha  Female       78     71       67       71
8    dinesh    Male       56     45       67       45
9      hema  Female       71     90       23       90
10    gowri  Female      100    100      100      100
11      ram    Male       78     55       47       55
12  murugan    Male       34     89       78       89
13  jenifer  Female       67     88       90       88
14   anjali  Female       92     97       90       88

In [17]:
# delete:
df.drop("science",axis=1)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    sundar    Male       12     67       67
7   kavitha  Female       78     71       67
8    dinesh    Male       56     45       67
9      hema  Female       71     90       23
10    gowri  Female      100    100      100
11      ram    Male       78     55       47
12  murugan    Male       34     89       78
13  jenifer  Female       67     88       90
14   anjali  Female       92     97       90

In [18]:
df.drop(14,axis=0)

       name  gender  physics  maths  english  science
0      arun    Male       88     87       78       87
1    rajesh    Male       96    100       95      100
2   moorthy    Male       89     90       70       90
3      raja    Male       30     25       40       25
4      usha  Female       67     45       78       45
5     priya  Female       56     46       78       46
6    sundar    Male       12     67       67       67
7   kavitha  Female       78     71       67       71
8    dinesh    Male       56     45       67       45
9      hema  Female       71     90       23       90
10    gowri  Female      100    100      100      100
11      ram    Male       78     55       47       55
12  murugan    Male       34     89       78       89
13  jenifer  Female       67     88       90       88

In [20]:
# delete column and row together :

In [29]:
# Date
df["dob"] = ['2005-08-04','2000-06-14','2001-02-24','2002-10-03','2001-04-07','2003-08-16','2002-05-01','2000-02-03','2006-08-21','2004-08-12','2003-01-31','2003-06-17','2002-02-04','2015-10-04','2015-08-24'
]
df

       name  gender  physics  maths  english  science         dob
0      arun    Male       88     87       78       87  2005-08-04
1    rajesh    Male       96    100       95      100  2000-06-14
2   moorthy    Male       89     90       70       90  2001-02-24
3      raja    Male       30     25       40       25  2002-10-03
4      usha  Female       67     45       78       45  2001-04-07
5     priya  Female       56     46       78       46  2003-08-16
6    sundar    Male       12     67       67       67  2002-05-01
7   kavitha  Female       78     71       67       71  2000-02-03
8    dinesh    Male       56     45       67       45  2006-08-21
9      hema  Female       71     90       23       90  2004-08-12
10    gowri  Female      100    100      100      100  2003-01-31
11      ram    Male       78     55       47       55  2003-06-17
12  murugan    Male       34     89       78       89  2002-02-04
13  jenifer  Female       67     88       90       88  2015-10-04
14   anjali  Female       92     97       90       88  2015-08-24

In [30]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [35]:
df['doj'] = ['2020-02-01','2021-01-01','2022-04-05','2019-05-01','2024-01-01']
print(df)
df['doj'].dtype
# convert string to date
df['doj'] = pd.to_datetime(df['doj'])
df['doj'].dtype

       name  roll no  marks         doj
0   dheeraj      123     10  2020-02-01
1     kunal     1234     20  2021-01-01
2  abhishek    12345     30  2022-04-05
3   praveen    12356     40  2019-05-01
4    anjali  1234567     50  2024-01-01

dtype('<M8[ns]')

In [38]:
# Day name :-
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name()

0     Saturday
1       Friday
2      Tuesday
3    Wednesday
4       Monday
Name: doj, dtype: object

In [40]:
df['doj'] + pd.to_timedelta("20 days")

0   2020-02-21
1   2021-01-21
2   2022-04-25
3   2019-05-21
4   2024-01-21
Name: doj, dtype: datetime64[ns]

In [46]:
df['doj'] + pd.to_timedelta("2")

0   2020-02-01 00:00:00.000000002
1   2021-01-01 00:00:00.000000002
2   2022-04-05 00:00:00.000000002
3   2019-05-01 00:00:00.000000002
4   2024-01-01 00:00:00.000000002
Name: doj, dtype: datetime64[ns]